install.packages("pryr")
require(pryr)
require(ISLR)
require(boot)
install.packages("plyr")
library(data.table)
library(plyr)
Students <- read.table(file.choose(),header=TRUE,sep=",")
Students2 = ddply(Students,"Sex",transform, Grade.Average=mean(Grade))
write.table(Students2,"Sorted_Average")
write.table(Students2,"Sorted_Average",sep=",")
